# Generated by Django 5.1.2 on 2024-10-24 19:37

import common.generators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('key', models.CharField(auto_created=True, default=common.generators.customer_key_generator, editable=False, max_length=10, unique=True)),
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=9)),
                ('location', models.CharField(max_length=200)),
                ('geo_location', models.URLField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
