# Generated by Django 5.1.2 on 2024-11-06 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='location',
            new_name='address',
        ),
    ]
