# Generated by Django 5.1.2 on 2024-11-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courier',
            options={'ordering': ['first_name']},
        ),
        migrations.AddField(
            model_name='courier',
            name='payload',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
