# Generated by Django 5.1.2 on 2024-11-10 03:13

import common.generators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_alter_courier_options_courier_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='login',
            field=models.CharField(default=1, editable=False, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courier',
            name='password',
            field=models.CharField(auto_created=True, default=common.generators.courier_password_generator, max_length=8),
        ),
    ]
