# Generated by Django 5.1.2 on 2024-11-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0003_courier_login_courier_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='login',
        ),
        migrations.AddField(
            model_name='courier',
            name='phone_number',
            field=models.CharField(default=1, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
