# Generated by Django 5.1.2 on 2024-11-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0004_remove_courier_login_courier_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='photo_uri',
        ),
        migrations.AddField(
            model_name='courier',
            name='car_number',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
