# Generated by Django 5.1.2 on 2024-11-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0005_remove_courier_photo_uri_courier_car_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
