# Generated by Django 5.1.2 on 2024-11-06 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_courier_alter_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='location',
            new_name='destination',
        ),
    ]
