# Generated by Django 5.1.2 on 2024-11-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_options_alter_order_new_bottles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='order',
            name='geo_location',
        ),
    ]
